### PR TITLE
edited survey questions

### LINKED ISSUE #61: PPT-024 - Update survey (reduce questions and enhance)

### PR DESCRIPTION
**Pull request by ravenclaw1999**
I removed major, source of income, and housing questions. Also, edited notification preference to not include "only when I am nearing budget option" for the time being due to constraints with sending notifications.

### CODE REVIEW

**Comment by ravenclaw1999** [comment]
Should we remove the notification method as well?

**Comment by aappacode** [comment]
> Should we remove the notification method as well?

what notification method? do you mean cell/email?

**Comment by ravenclaw1999** [comment]
> > Should we remove the notification method as well?
> 
> what notification method? do you mean cell/email?

Yep!

**Comment by ravenclaw1999** [comment]
@aappacode Let me know if I should merge the questions as is, or change anything else. Thanks!

**Comment by aappacode** [comment]
> > > Should we remove the notification method as well?
> > 
> > 
> > what notification method? do you mean cell/email?
> 
> Yep!

you can keep this for now!

**Comment by aappacode** [comment]
> @aappacode Let me know if I should merge the questions as is, or change anything else. Thanks!

is there a quick way to hide the "notification method" dropdown if the user clicks never? If not, we can just merge
Screenshot 2023-11-13 at 3 24 28 AM

Also-- college/university and notification preferences just needs a colon after it LOL but rest looks great!!

You can also choose to remove all the colons, up to you!

**Pull request merged**
