### PR TITLE
Connect transaction table with DB

### LINKED ISSUE #41: PPT-019 - Update backend for transactions table/add transaction
Every time a user adds a transaction, it should be saved to their user information/database so when they log back in, that information is saved there. The category selection should match the survey output.

### PR DESCRIPTION
**Pull request by chaol12**
create a new collection in DB firestore that called 'User_TransactionDoc' to save individual user transaction. In reat,  add the addTransactionToDb() function and getTransactionFromDB() in firebase-config.js. And modify adding a new transaction description input field.

### CODE REVIEW

**Comment by aappacode** [comment]
Samira: brought up merge conflict issues

**Comment by ravenclaw1999** [comment]
I don't think phone number is collected anywhere, either during registration or survey. Do you think it's a good idea to just add it to survey?

**Comment by ravenclaw1999** [comment]
Small thing, but I think some of these categories for the dropdown can be combined / removed:

```
    const listOfExpenses  = [
      'Food', 'Groceries', 'Dining Out', 'Snacks', 'Transportation','Textbooks ', 'Utilities',
      'Tuition', 'Entertainment', 'Cell Phone Bill','Healthcare','Shopping','Clothing',
      'Electronics', 'Home Goods','TextBooks','Supplies','Investments','Gifts','Haircut/Beauty',
      'Subscriptions','Travel','Taxes','Other']
```

For example, we can remove shopping since there are separate categories for clothing, home goods, etc.  Also, 'supplies' is pretty vague. This will make it easier for visualizing the transactions or categorizing the transactions in the future.

**Comment by ravenclaw1999** [comment]
Could you fix the button so it shows even when the user doesn't have any transactions?
Screenshot 2023-11-08 at 8 44 22 PM

**Comment by ravenclaw1999** [comment]
Not sure if it's on my end, but I don't see the new changes you made with the popup. I cloned from your fork.
Screenshot 2023-11-08 at 8 45 26 PM

**Comment by ravenclaw1999** [comment]
Never mind, I can see your changes now!

Can you add a check to make sure the user can't type in a negative number for the amount?
Screenshot 2023-11-08 at 9 30 54 PM

**Comment by ravenclaw1999** [comment]
Also, would it be good to also allow them to type in a specific date for their transactions? Assuming they aren't typing in their transactions daily. I guess that can also be remedied if we connect directly to their bank account. What do you think?

**Pull request closed without merging**
