### PR TITLE
added navBar and integration

### PR DESCRIPTION
**Pull request by gaoqiangzhou**

### CODE REVIEW

**Comment by ravenclaw1999** [comment]
Should we include only 'login' on the navbar? Then, if they aren't registered, there will be an option to be routed to the registration form.

**Comment by ravenclaw1999** [comment]
Are there also other navlinks that could be good to include such as the dashboard, profile, etc.? We would add the temporary routes for those. @gaoqiangzhou

**Comment by gaoqiangzhou** [comment]
`include only 'login' on the navbar` is a good idea, there need to be a register button added to the login page
`other navlinks` will be added by Sunday as we discussed in the meeting when other pages are merged @ravenclaw1999

**Comment by ravenclaw1999** [comment]
Sounds good, we can update the navbar once we have the updated register page.

**Pull request merged**
