### PR TITLE
noel- added transaction table to dashboard page 

### LINKED ISSUE #6: PPT-005 -- Create Transactions Table
Filtered by date, category, and transaction total per item

### PR DESCRIPTION
**Pull request by noelsmathew**

### CODE REVIEW

**Comment by aappacode** [comment]
combining dash cards and transaction table

**Review by aappacode — APPROVED** [review]
The combined code looks good!

**Comment by ravenclaw1999** [comment]
Would the 'budget spent' be the total amount for all the transactions combined?

**Comment by ravenclaw1999** [comment]
Maybe we can add a 'Total Spent' at the bottom of the transactions?

**Comment by aappacode** [comment]
> Would the 'budget spent' be the total amount for all the transactions combined?

Yes, but looking to the next iteration to decide best placement

**Pull request merged**
