### PR TITLE
More tests 2

### PR DESCRIPTION
**Pull request by gaoqiangzhou**
image

### CODE REVIEW

**Comment by gaoqiangzhou** [comment]
image

**Comment by ravenclaw1999** [comment]
So, TransTable.jsx is the only file left to write unit test cases for? I will write it once the new changes are merged in

**Comment by ravenclaw1999** [comment]
It seems the github action failed with this error:

Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package). 

Is there something I am missing in the Profile.jsx file in addition to the following line?

`/* istanbul ignore file */`

**Comment by ravenclaw1999** [comment]
Screenshot 2023-12-17 at 12 19 46 AM

All tests pass.

**Review by ravenclaw1999 — APPROVED** [review]

**Pull request merged**
