### PR TITLE
Data Visualization Page

### PR DESCRIPTION
**Pull request by noelsmathew**
Data Vis Page
- lineChart: showcases daily spend, total spend, monthly budget
- areaChart: tracks whether the user has met their savings goal
- PieChart: shows top 4 categories of spend

### CODE REVIEW

**Comment by aappacode** [comment]
fixed conflict for u 👯‍♀️

**Comment by aappacode** [comment]
Screenshot 2023-12-04 at 6 30 45 AM

load is still problematic also this is dark mode (ignore)

**Comment by noelsmathew** [comment]
Current layout arrow has been modified to reflect negative or positive percentage of savings, load is still trying to be fixed
Screen Shot 2023-12-04 at 3 03 08 PM

**Review by aappacode — APPROVED** [review]
tenative approval for demo

**Pull request merged**
