### PR TITLE
[REFACTOR] DB correctly renders user data

### PR DESCRIPTION
**Pull request by zikrya**
I removed the user collection, and then rendered the contents of the survey collection onto the Profile.jsx. Came into based on the db not distinguishing the users, which was a simple fix.

### CODE REVIEW

**Comment by ravenclaw1999** [comment]
Should we remove the users collection on firestore?

**Comment by ravenclaw1999** [comment]
Great, now survey results have the user id attached and the profile page populates accordingly. Since the previous survey answers don't have a user id attached, we should delete them to avoid confusion.

**Comment by ravenclaw1999** [comment]
I don't think phone number is collected anywhere, either during registration or survey. Do you think it's a good idea to just add it to survey?

**Comment by aappacode** [comment]
> I don't think phone number is collected anywhere, either during registration or survey. Do you think it's a good idea to just add it to survey?

phone number may be used for notifications so yes

**Pull request merged**
