### PR TITLE
[RESPONSIVE DESIGN] Added web responsive design to dashboard page

### LINKED ISSUE #98: Make pages responsive (especially dashboard)

### PR DESCRIPTION
**Pull request by ravenclaw1999**
With this PR, the dashboard is a lot more responsive on smaller devices. Text, buttons, the table, etc. are all adjusted according to the device or screen window. Media queries were added to make it responsive.

Example:

Screenshot 2023-12-04 at 2 04 47 AM

Screenshot 2023-12-04 at 2 04 57 AM

Here's how it looks on a bigger screen:

Screenshot 2023-12-04 at 2 11 13 AM

For issue #98

### CODE REVIEW

**Comment by aappacode** [comment]
let's just wait on zack's survey fix then review/merge this after!

**Comment by aappacode** [comment]
is there an easy way to make the new transaction button on the phone size "sticky" so that it stays on the bottom of the screen even if the user is scrolling down on the transactions table?

**Comment by ravenclaw1999** [comment]
Is this good? 

Screenshot 2023-12-04 at 12 15 34 PM

**Comment by aappacode** [comment]
> Is this good?
> 
> Screenshot 2023-12-04 at 12 15 34 PM

yesssss

**Review by aappacode — APPROVED** [review]
Added comments that were addressed (see pr)

**Pull request merged**
