### PR TITLE
Adding tests

### PR DESCRIPTION
**Pull request by gaoqiangzhou**
Keep adding tests in this branch....

### CODE REVIEW

**Comment by gaoqiangzhou** [comment]
image

**Comment by ravenclaw1999** [comment]
This should be reviewed, updated, and merged once all code has been merged, as not to cause more conflicts and errors.

**Comment by ravenclaw1999** [comment]
How do I run these tests? I think you previously mentioned that there was some issue with the jest.

**Comment by ravenclaw1999** [comment]
Do you know why the Survey.test.js file takes so long to run?

**Comment by ravenclaw1999** [comment]
Is it because of the survey bug that was merged into main earlier? Since you have an older working version.

**Comment by ravenclaw1999** [comment]
Are there any kind of test cases we need written for the database, like the firebase config file?

Here's the coverage I am seeing on my end:

Screenshot 2023-12-03 at 5 49 20 PM

**Comment by gaoqiangzhou** [comment]
> Are there any kind of test cases we need written for the database, like the firebase config file?
> 
> Here's the coverage I am seeing on my end:
> 
> Screenshot 2023-12-03 at 5 49 20 PM

Its hard to test a third-party lib. And its harder to test when it involves API requests. The coverage should be good once the survey, transtable and profile is tested

**Review by ravenclaw1999 — APPROVED** [review]

**Pull request merged**
