### PR TITLE
pwa deployed

### LINKED ISSUE #54: PPT-023 - Make app a PWA + responsiveness on different screen size

### PR DESCRIPTION
**Pull request by gaoqiangzhou**
pwa deployed, can now install the app on local device 
Screenshot 2023-11-13 191333

### CODE REVIEW

**Comment by zikrya** [comment]
You did a great job! However there's only a minor problem in the frontend 
Screen Shot 2023-11-19 at 3 50 56 PM
You can see that the
 $100 to the goal! 
 is a bit off centered in mobile mode, can you fix that, and this should be all set to merge!

Best,
Zikrya

**Comment by gaoqiangzhou** [comment]
image
should be good now

**Review by aappacode — APPROVED** [review]
This PWA looks good and was reviewed by Zack, we will use these practices for other parts of the application (e.g. Noel and I are developing the data visualizations page)

**Comment by zikrya** [comment]
Look good! Merged!

Best,
Zikrya

**Pull request merged**
