### PR TITLE
[ADDED] Report Budget

### LINKED ISSUE #92: Generate user's quarterly report on-click of button

### PR DESCRIPTION
**Pull request by zikrya**
This works, but I don't know where we would like to place the generate report button, so it looks out of place

### CODE REVIEW

**Comment by aappacode** [comment]
@zikrya is there a way to add transactions total here as well?

**Comment by aappacode** [comment]
@zikrya can you add a button for "View Data Visuals" (you can add dummy code, this will navigate to the data visualization page) under the add transaction button? We can then add the generate pdf on the data vis page and this page (you can also add another button to that right column)

**Comment by zikrya** [comment]
> @zikrya is there a way to add transactions total here as well?

I can but I don't know if I'll have time to get it done.

Best,
Zikrya

**Comment by zikrya** [comment]
> @zikrya can you add a button for "View Data Visuals" (you can add dummy code, this will navigate to the data visualization page) under the add transaction button? We can then add the generate pdf on the data vis page and this page (you can also add another button to that right column)

Can you clarify on what you mean?

Best,
Zikrya

**Comment by aappacode** [comment]
> Can you clarify on what you mean?

nevermind, i can add it in later!

**Review by aappacode — APPROVED** [review]
Tested the changes by pulling into my branch and left comments on what shows up in the pdf--enhancement feature currently captures transaction table for pdf downloading. Will need to resolve conflicts first! For the merge conflicts, i just copy and paste the current package.json files and then re-do the npm installations you need for pdf

**Pull request closed without merging**
